version: 1

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/sc/main.go
    binary: sc
    ldflags: -s -w -X main.version={{.Version}} -X main.date={{.Date}}


dockers:
  - image_templates:
      - "ghcr.io/uvasoftware/scanii-cli:{{.Tag}}"
      - "ghcr.io/uvasoftware/scanii-cli:latest"
report_sizes: true
archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

gomod:
  mod: mod
